- name: 'gcommands changes'
  color: '5663e9'
- name: 'discord.js changes'
  color: '5663e9'
- name: 'bug'
  color: 'f02b56'
- name: 'discussion'
  color: 'ffffff'
- name: 'has PR'
  color: '4b1f8e'
- name: 'in progress'
  color: 'ffccd7'
- name: 'question'
  color: 'd147cf'
- name: 'wontfix'
  color: 'ffffff'
- name: 'dependencies'
  color: '276bd1'
- name: 'chore'
  color: 'ffffff'
- name: 'feature request'
  color: 'fcf95a'